### ISSUE TITLE
Document design decisions

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/dist.spec#7]
Let's take a step back and have a call to brainstorm and document the design decisions we want to stick to here. This will also capture wider interoperability issues (related: #6 and https://github.com/epiforecasts/EpiNow2/issues/823#issuecomment-2397360683)

**Comment by sbfnk** [comment]
Just noting that we've already got https://github.com/epiforecasts/dist.spec/blob/main/inst/design.md

**Comment by jamesmbaazam** [comment]
Yes, I had that in mind as a starting point. I think we should make it a vignette to properly expose it, though. 

I'm also not exactly sure how the other packages would adopt it into their current infrastructure or how much breaking changes they'd need to make to adopt this package. It would be good to access that by engaging with the developers of the listed packages.

**Comment by seabbs** [comment]
Noting for future reference I don't think we need to target `epidist` as that uses the `brms` tooling natively (though happy to hear why we might want to do that)/

**Comment by seabbs** [comment]
> Any EpiNow2 specific functionality (especially relating to conversion to stan code) should not interfere with core functionality of the distribution interface.

I think `primarycensored` shows a model for how to do this and also others the hope that this functionality doesn't need to be designed as `EpiNow2` only.

**Comment by jamesmbaazam** [comment]
I'm yet to review `primarycensored` but will make a top to-do. I've heard a lot of good things about it 😉

**Comment by seabbs** [comment]
I mean only 1 person is interested and they say its great (its me)

**Comment by seabbs** [comment]
The TLDR is we ship stan code inside the R code and provides some tools to get at it and put it in peoples models either at run time or by developers. Its not ideal but its better than copy and pasting

**Comment by jamesmbaazam** [comment]
Closing this issue the suggested document already exists, although I think it's better stored as a vignette.
